### ISSUE TITLE
Saved setting causing crash on start 

### ISSUE THREAD

**Issue by marcusbirkin** [docsteer/sacnview#104]
Forked from #97 
@dtdickman has an issue with crashing on startup related to a saved mac address setting

**Comment by marcusbirkin** [comment]
@dtdickman Could you let me know the MAC address, as saved in the registry, that causes this issue.
Could you also post the output from the command line "ipconfig /all".

Does selecting any interface on first start always cause the next starts to fail? Or is it completely related to a single interface?

**Comment by marcusbirkin** [comment]
@dtdickman Could you confirm if you are still seeing this issue on v2.0.1RC2?

**Comment by dtdickman** [comment]
Yes, Still seeing the issue in v2.0.1RC2

**Comment by marcusbirkin** [comment]
Could you post the settings from the registry and the output from "ipconfig /all"?

**Comment by dtdickman** [comment]
Here are the registry settings and the ipconfig output. IP config has been blocked out a bit for the privacy of the company I work for. I can send to you privately if you need.
![registrysettings](https://user-images.githubusercontent.com/5060112/36793929-d38d16d4-1c6c-11e8-8f2e-ceeeeeacaf73.PNG)
![ipconfig 1of2](https://user-images.githubusercontent.com/5060112/36793936-da164566-1c6c-11e8-879b-1a324184f90f.jpg)
![ipconfig 2of2](https://user-images.githubusercontent.com/5060112/36793938-da91ee50-1c6c-11e8-8c4e-fa9d25d42058.jpg)

**Comment by marcusbirkin** [comment]
We believe we have a fix, and it's a issue with the firewall checker.
Do you use the built in Windows firewall or have you a third party firewall installed?

**Comment by docsteer** [comment]
We believe we have this fixed in v2.0.1 RC3 - please give the latest a try and let us know if there are still issues!

**Comment by tw0fer** [comment]
This is working for me!! Thanks for all of your help!
