### ISSUE TITLE
Add indication for unable to bind sockets

### ISSUE THREAD

**Issue by docsteer** [docsteer/sacnview#110]
This was discovered while trying to run Madrix software (https://www.madrix.com/support/download) and sACNView at the same time.

Madrix exclusively binds the sACN multicast groups, so it looks like sACNView can't see the data if it is run after Madrix has been started.

Would be good to have some kind of indication, maybe in the universe tree, that we can't bind those groups. At the moment no way to figure this out without seeing the debug messages

**Comment by marcusbirkin** [comment]
Resolved in 2.1-dev
