### ISSUE TITLE
Icons appear huge in Windows 10 4k resolution

### ISSUE THREAD

**Issue by Lozzy0603** [docsteer/sacnview#115]
Toolbar icons appear huge / badly scaled in Windows 10 with a 4k resolution. This is without High DPI scaling enabled as the application is tagged high-dpi aware.
If you enable High-DPI compatability mode, system enhanced, icons are slightly smaller.
System resolution is 3840*2160 native.
![clipboard01](https://user-images.githubusercontent.com/32219797/36375416-193f038e-1567-11e8-89b6-04d82abb5c74.png)

**Comment by docsteer** [comment]
We think this is improved in the 2.1 beta - but if anyone who has Win10 high res can test it and let us know that would be great!

**Comment by Lozzy0603** [comment]
Fixed! Thanks!

**Comment by marcusbirkin** [comment]
Glad this worked as I was only able to test it on a virtual Linux desktop!
