### ISSUE TITLE
Search for sACN universes with active data..... and search for source by IP

### ISSUE THREAD

**Issue by tw0fer** [docsteer/sacnview#116]
Hey there,

2 questions here....

Is there a quick/easy way to search the network and list all universes that have active sACN data? I'm thinking something like an IP scanner but for sACN universes.

Also, If I know the IP of source, Is there a way to search for the specific source and then list which universes it is outputting?

Thanks!

**Comment by marcusbirkin** [comment]
Hi,

We can certainly look at putting this in.

We should also look at expanding support to E1.31:2016 which includes universe discovery.

**Comment by marcusbirkin** [comment]
E1.31:2016 universe discovery, where supported by senders, has been added to v2.1
Adding a scanning feature for all universes would be impractical do to the sheer number of possible universes (63999) and the need to join and release large numbers of multicast groups.
