### ISSUE TITLE
Documentation missing "Jumps"

### ISSUE THREAD

**Issue by fealXX** [docsteer/sacnview#126]
Hi there,
I can't find a definition in the documentation (explaning the universeview) for the "Jumps" column.

![image](https://user-images.githubusercontent.com/7534146/38544866-e6224cb8-3ca8-11e8-989a-b6871e3a0265.png)

Can anyone give me a hint where to find it or what it means?

Thanks,
Felix

**Comment by marcusbirkin** [comment]
Should implement tooltips

**Comment by mrrodgers23** [comment]
sACN is a UDP transmission, correct?  How does sACNView detect packet losses without a handshake between hosts?

> Hi Felix,
> 
> Jump is a lost packet.
> E.G. we get packet 1, then 3, but not 2
> 
> SeqErr is a packet arrived out of sequence.
> E.G. We get packet 1, then 3, then 2
> 
> From your screen shot it appears you are getting network packet loss.

**Comment by docsteer** [comment]
There's now a full description of jumps and sequence errors in the 2.1 documentation at https://github.com/docsteer/sacnview/blob/2.1-dev/docs/documentation.md - this will appear on the main site when we make 2.1 a full release.

To answer @mrrodgers23 question, each sACN packet contains a sequence number that increments with every packet from a source - that allows us to track lost or out of order delivery
