### ISSUE TITLE
Transmit keypad - FULL without preceeding AT is not handled properly

### ISSUE THREAD

**Issue by docsteer** [docsteer/sacnview#134]
Pressing 1 THRU 24 FULL, makes the command line show 1 THRU 24 @ FULL* but doesn’t actually output.
Currently you must press 1 THRU 24 AT FULL, to get output

**Comment by marcusbirkin** [comment]
Resolved in #138

**Comment by docsteer** [comment]
Fixed in 2.1.0 beta 1, but I just noticed that 1 THRU 24 AT 100 is now broken.. leaving this open as a reminder to fix that!

**Comment by marcusbirkin** [comment]
Resolved repeating last digits in https://github.com/docsteer/sacnview/commit/dbd5517ed5b41c363bfedb9373b4825dfc2daf14

**Comment by docsteer** [comment]
Fixed in 2.1.0 beta 2
