### ISSUE TITLE
Command Line Keyboard Shortcuts

### ISSUE THREAD

**Issue by SammyTheHand** [docsteer/sacnview#144]
Could we have keyboard shortcuts for the keys within the Transmit Faders Tab:
Thru = t
At = a
Clear = Backspace
And = +
Enter = Return
Full = f
All Off = o

**Comment by marcusbirkin** [comment]
Would appear that these are already in, but not always active!
fbc848e79b0e29818836221f97da855748b8132a Makes command widget have strong focus and adds a cursor to make it clear when keyboard input can be accepted!
