### ISSUE TITLE
When starting the transmit dialog with levels already present, the fader levels are applied first

### ISSUE THREAD

**Issue by docsteer** [docsteer/sacnview#145]
If you want to start a source with levels already present, if you go into effects and set a manual level, then stop and start the source, the fader levels are applied first, then the manual level is applied after a few frames.

This should probably be fixed by not disabling the controls when a source is inactive, so you can setup whatever you want, and then start transmitting.

**Comment by marcusbirkin** [comment]
Implemented in v2.1beta3
