### ISSUE TITLE
Resizing of Universe View offsets the mouse click area

### ISSUE THREAD

**Issue by tomsmcguire** [docsteer/sacnview#151]
![sacn bug](https://user-images.githubusercontent.com/40663071/42043607-c6e7fb2a-7aee-11e8-8fad-540e0d78e0e0.gif)

In the attached gif you can see when i click at normal size everything lines up.
When I pull the window bigger it seems the detect area for selection moves rather than stretches with the window so everything lower down doesn't where you expect it.

**Comment by marcusbirkin** [comment]
Resolved in f4be2204

**Comment by docsteer** [comment]
Included in 2.1.0 beta 2
