### ISSUE TITLE
Transmitter - Cannot manually enter Channel Fade Range

### ISSUE THREAD

**Issue by EVeik** [docsteer/sacnview#160]
Attempted to enter manual channel numbers for fade range in transmitter.  Only way to change numbers is using + and - buttons.  Previous release allowed this.

**Comment by marcusbirkin** [comment]
opps, resolved in 00ba6b4e5931cc53c4a44e37aa2cfa0ca5a57c25

**Comment by docsteer** [comment]
Fixed in 2.1.0 beta 2
