### ISSUE TITLE
About page missing URL (clickable link would be nice)...

### ISSUE THREAD

**Issue by VoltVisionFrenchy** [docsteer/sacnview#161]
When clicking the "i" for the "About Page", there are no live links nor references to the most recent URL for "sACN View".  Currently there are only two clickable-links for licenses.  This would be useful for people wanting to get to your website, view the documentation or even get to the code on github.
 
ps-I love this program and I find it ultra-useful.  Thankyou!

**Comment by docsteer** [comment]
Resolved in v2.1.0 Beta 2
