### ISSUE TITLE
Universe List shows each source twice

### ISSUE THREAD

**Issue by RichardTea** [docsteer/sacnview#166]
Found in v2.1.0-beta.2

The Universe List shows each source twice, while the Universe View only shows each source once.
![sacnview210beta2](https://user-images.githubusercontent.com/31507749/48833193-bdbaf100-ed72-11e8-8fe6-a5af0963c10e.png)

**Comment by marcusbirkin** [comment]
Thanks - Sorted!

**Comment by docsteer** [comment]
Fixed in 2.1 beta 3
