### ISSUE TITLE
Crash when trying to transmit text

### ISSUE THREAD

**Issue by johnhart96** [docsteer/sacnview#180]
Trying to transmit the text Universe 1 on sACN universe 1. When clicking start I get a crash. Running Version 2.1.0 beta 3

Dump file: [https://www.dropbox.com/s/xguknlf6debltzi/69c3b976-1f58-40a0-99fd-599afe991a88.dmp?dl=0](url)

**Comment by docsteer** [comment]
Should be fixed in 2.1.0 beta 4
