### ISSUE TITLE
Add a fade rate of 44Hz

### ISSUE THREAD

**Issue by docsteer** [docsteer/sacnview#187]
To make the program useful as a test tool, a fade driven at the max fade rate of 44Hz would be useful to have single packet ticks of one level increment

**Comment by marcusbirkin** [comment]
It appears that the effect engine output is actually unable to maintain the rates currently prescribed.
E.g. Setting 25Hz results in about 20-21Hz output

**Comment by marcusbirkin** [comment]
Very likely that incorrect rate is resolved by #196
