### ISSUE TITLE
Crash when sending Per Address Priority with less than 512 slots.

### ISSUE THREAD

**Issue by jtveite** [docsteer/sacnview#189]
If you attempt to send a universe with per address priority and also not all of the slots, sACN viewer crashes. Testing with 511 seems to work fine, 257 crashes immediately, and 5 or 50 crashes immediately and also fails to create a dump succesfully/doesn't display the usual crash dump dialog, just gets a stopped working from Windows.

I've attached a zip that has 3 dumps in it: 5866... and fc07... were from the times with ~257 slots and 0797... is from one of the times where it failed to dump properly (and appears to be 0 bytes so may not be useful).
[sacnviewercrash.zip](https://github.com/docsteer/sacnview/files/3208474/sacnviewercrash.zip)

**Comment by marcusbirkin** [comment]
Which version of sACNView are you running?

**Comment by jtveite** [comment]
This was with v2.1.0-beta.4

**Comment by marcusbirkin** [comment]
Resolved, thanks for letting us know!
