### ISSUE TITLE
Packets with a synchronization address are considered invalid

### ISSUE THREAD

**Issue by mattbeghin** [docsteer/sacnview#198]
In streamcommon.cpp, the code in VerifyStreamHeader / line 340
```
  if(UpackB2(pbuf + RESERVED_ADDR) != RESERVED_VALUE)
  { 
      return false;
  }
```
will exclude any packet with a synchronization address. You can test with the demo version of MadMapper which handles synchronization.

**Comment by marcusbirkin** [comment]
Synchronization packets are not currenlty supported in sACNView.
It's certainly something that could be added later, but some thought would need to be had as to how this is displayed. 
For now anything with the vector VECTOR_E131_EXTENDED_SYNCHRONIZATION is ignored

**Comment by mattbeghin** [comment]
Why not just ignoring this field, so at least you could monitor data coming from an application that handles synchronization ?

**Comment by BlakeGarner** [comment]
As per mattbeghin's comment: as currently implemented, not only are synchronization packets being dropped, but so are valid E1.31 data packets that happen to have the synchronization field (formerly reserved field) set. As per the 2018 spec, 6.2.4.1: 
> When receiving an E1.31 Data Packet with a nonzero Synchronization Address, any receiver which does not support universe synchronization shall ignore the Synchronization Address and process the received data stream normally.

And the 2009 spec, section 4, octets 109-110:
> Reserved: Transmitter Shall Send 0, Receivers Shall Ignore.

While adding synchronization support is an enhancement, I believe the issue described here (dropping data packets if the synchronization address is != 0) is a bug.

**Comment by mattbeghin** [comment]
Indeed it's a bug, many of our users use SacnView and think there's a bug on our side. I send them a build with the fix I mentioned here so they can see what we send.

**Comment by marcusbirkin** [comment]
@mattbeghin and/or @BlakeGarner please submit a pull request for your proposed changes.
