### ISSUE TITLE
Web link in About is bad

### ISSUE THREAD

**Issue by matt-pumplin** [docsteer/sacnview#201]
In about, there's a weblink.  It points to https://www.sacnview.org/sacnview/
Google tells me that page doesn't exist :-\
![image](https://user-images.githubusercontent.com/32332797/67048507-f6398b00-f0f9-11e9-908b-7a022878f80b.png)

**Comment by marcusbirkin** [comment]
D'oh
Resolved with https://github.com/docsteer/sacnview/commit/505b21f82e96a94abe264a3080ddd6e1840e9b29
