### ISSUE TITLE
Unable to listen on localhost in latest version

### ISSUE THREAD

**Issue by HughMacdonald** [docsteer/sacnview#203]
Hi,

I updated sACNView earlier today when prompted, and found that I was unable to listen on 127.0.0.1, which I had been able to previously. Is this something that I should be able to do?

I've been using it to check sACN data on a project I'm working on at the moment, so am doing all of my work on localhost.

Is there a way to do this that I'm missing? And if not, would it be possible to bring back the ability to listen on localhost in a future release?

Thanks

**Comment by docsteer** [comment]
Oops! So you can do that from the initial network selection dialog by clicking the work offline button:
![image](https://user-images.githubusercontent.com/15143933/67896305-191c6400-fb2a-11e9-8c07-6257674ad34f.png)

However, if you've selected another interface you won't see that dialog again until your network configuration changes. This is a bug - for now a workaround would be to delete the registry key (HKEY_CURRENT_USER\Software\sACNView) if you're on Windows, and then the dialog will show on startup.

**Comment by HughMacdonald** [comment]
Thanks for the work-around - I'll do that then (I'm not using it in anything other than localhost mode right now)

**Comment by docsteer** [comment]
Fixed in v2.1.1
