### ISSUE TITLE
Documentation clarification request

### ISSUE THREAD

**Issue by david-nelson** [docsteer/sacnview#204]
The documentation says:

“Sequence Errors - A sequence error is specifically defined in the sACN Standard for packets which are missing or out of order. If you get frequent sequence errors, there may be a problem with your network.

Jumps - A jump, unlike a sequence error, indicates any packets which are delivered out of order or dropped. One or two jumps are not unusual over time, but if you see many jumps you may have a network problem.”

It’s not clear what is included in “any” packets which might be counted in the Jumps counter.  Any packets, of any protocol, destined for any host that have dropped or out of sequence delivery?  I’m using the program to monitor the local Ethernet interface on the same computer and I see thousands of Jumps counts.  It’s a small private network, so the high rate of Jumps is unexpected.  The explanation in the documentation doesn’t give sufficient description to allow valid inferences to be drawn.

**Comment by marcusbirkin** [comment]
Jump is a lost sACN packet.
E.G. we get packet 1, then 3, but not 2

SeqErr is an sACN packet arrived out of sequence.
E.G. We get packet 1, then 3, then 2
