### ISSUE TITLE
Is there a way to put sacnview in promiscuous mode to see unicast packets?

### ISSUE THREAD

**Issue by TechplexEngineer** [docsteer/sacnview#205]
When using sACN over unicast is there a way to view the network traffic in sacnview?

**Comment by marcusbirkin** [comment]
It does not, that would require kernel level access for most operating systems.
Note most networks operate with a switch (and not a hub) promiscuous mode wouldn't actually work unless you specifically install a hub or setup your switcher to forwards all packets (SPAN port).

What you can do, is to capture the traffic with wireshark and play this back.

**Comment by TechplexEngineer** [comment]
Thanks for the reply.
Luckily I can see the traffic with wireshark, but the dissector doesn't show the channels and their values.

Are you saying that if I use wireshark to capture the acn traffic into a pcap file I can view that pcap in sacnview?

**Comment by marcusbirkin** [comment]
Yes you can playback pcap files, have a butchers at this: https://github.com/docsteer/sacnview/blob/master/docs/documentation.md
