### ISSUE TITLE
Levels dont persist in transmit mode when switching from Faders to Grid Control Tab

### ISSUE THREAD

**Issue by ferreez** [docsteer/sacnview#207]
if you are outputting levels in the faders tab and you switch over to the grid control tab the levels you were sending show up in the grid but are not actually outputting.
if you change the level in grid view it will begin to output.
this happens every time you switch from faders to grid. 
it doesnt happen if you switch from grid to faders (even if grid isnt actually putting out levels)

**Comment by docsteer** [comment]
Fixed in v2.1.1
