### ISSUE TITLE
v2.1.0 Mac - Recording Preset Recall Crashes Program

### ISSUE THREAD

**Issue by jabadger** [docsteer/sacnview#208]
-Open transmit window.
-Drag fader 12 to full.
-Click preset record.
-Click preset 1. Software Crash.

Crash log attached.
[sACNView_2020-04-30-164431_lappy-l09.crash.zip](https://github.com/docsteer/sacnview/files/4561894/sACNView_2020-04-30-164431_lappy-l09.crash.zip)

**Comment by marcusbirkin** [comment]
Workaround: Start sending before recording presets
