### ISSUE TITLE
Universe Discovery Messages with Full Payload Rejected

### ISSUE THREAD

**Issue by Crackerjack55** [docsteer/sacnview#224]
It appears that universe discovery messages populated with a full payload of 512 universes are discarded. This appears to be because of two factors:

In sacndiscovery.h - line 15
`#define E131_UNIVERSE_DISCOVERY_SIZE_MAX 1143`
Should be
`#define E131_UNIVERSE_DISCOVERY_SIZE_MAX 1144`

and 
in sacndiscovery.cpp - line 240
The condition 
`!(buflen < E131_UNIVERSE_DISCOVERY_SIZE_MAX))`
should be
`!(buflen <= E131_UNIVERSE_DISCOVERY_SIZE_MAX))`

According to the standard 
"The Universe Discovery Layer PDU length is computed starting with octet 112 and continuing through the last universe provided in the Universe Discovery PDU (octet 1143 for a full payload). This is the length of the Universe Discovery PDU."

But since the octets are zero indexed - the actual max message size is 1144

----- 

Similarly - but much less important:
`if (!(buflen > E131_UNIVERSE_DISCOVERY_SIZE_MIN)`

The check should be >= as it is possible to broadcast universe discovery but not have any universes
 
"Any source that is no longer sending any universe data may stop sending E1.31 Universe Discovery Packets until such time that it resumes transmission of E1.31 Data and/or Synchronization information. It shall also be acceptable for such a source to continue sending E1.31 Universe Discovery Packets that contain an empty List of Universes."

That being said - it'd be hard to show an empty list of universes with the current view.

-----

Hope this helps

**Comment by marcusbirkin** [comment]
Off by one errors are my favourite!
Could you submit a pull request and I'll get it integrated.

Out of interest, what are you operating with that generates so many universes and uses discovery packets? I've yet to actually find any real world devices, bar sACNView, that uses discovery.

**Comment by Crackerjack55** [comment]
To be fair - the only reason I came across it was that my initial implementation was lazily sending a full payload of 8 universes followed by 504 'zeroes' rather than only sending the universes in use.

This was done for the purposes of the software, Disguise Designer, rather than a device per-say

I'll get the PR set up
