### ISSUE TITLE
Cannot launch sACNView on macOS Big Sur (hang)

### ISSUE THREAD

**Issue by Jeff0S** [docsteer/sacnview#229]
Just a heads up...

I did an error today: I upgraded to macOS Big Sur 11.0.1 => sACNView v2.1.1 hangs 
I can post the full report but not sure it'd be useful: it seems to be a known issue for all Qt-based (QML-based?) apps, it should be fixed in Qt 5.15.
=> I've cloned the project, built it on Big Sur against Qt 5.15.1 clang 64bit 
=> sACNView  works fine

**Comment by docsteer** [comment]
Fixed in 2.1.2 release
