### ISSUE TITLE
Migrate away from Travis

### ISSUE THREAD

**Issue by docsteer** [docsteer/sacnview#232]
Travis CI is closing travis-ci.org and the future usage of it for open source projects seems uncertain (see e.g. https://www.r-bloggers.com/2020/11/moving-away-from-travis-ci/)

We should migrate the linux and macos CI builds to something better/newer - github actions maybe?

**Comment by marcusbirkin** [comment]
About 8 months ago I was looking at using Appveyor for all the builds as they added MacOS support.
I got stuck with the create DMG issue, but that should be resolved now. 
I'll look at the branch again and make a pull if it's useable.

**Comment by docsteer** [comment]
v2.1.3 beta 1 is now released and on the website, and is built using github actions
