### ISSUE TITLE
Feature Request - RDMnet Support

### ISSUE THREAD

**Issue by samuelblakemore** [docsteer/sacnview#236]
It would be great if there was a feature that allowed for monitoring/configuring of fixtures using RDM / RDMnet. A fixture discovery tool and then the ability to export/import/save RDM(net) configurations.

I also second the 'buy a coffee' request!

**Comment by docsteer** [comment]
That would be a pretty big feature extension for this software - I think I'm going to say no I'm afraid, the goal of sACNView is just to show control levels, not provide complete system device management. Concert from ETC provides RDMnet device discovery/configuration in it's latest beta version and beyond, and ETC provides an example controller in their [Github project](https://github.com/ETCLabs/RDMnet) which is pretty usable.
