### ISSUE TITLE
SeqErr and Jumps on Linux

### ISSUE THREAD

**Issue by TheIncredibleMulk** [docsteer/sacnview#237]
# SeqErr and Jumps on Linux
### sACNview v2.1.2 running on Ubuntu 20.04.1. x64
If the `listen on all interfaces` option is chosen, then the SeqErr and Jumps start stacking up. If a specific interface is chosen, things function as usual. I've cross tested with Windows10 and cannot replicate the issue. 
What other info can help provide?

**Comment by marcusbirkin** [comment]
What is the source of sACN in this test?
How many active interfaces do you have?
Could you check using wireshark that you arn't infact receiving the same sACN from multiple interfaces?

**Comment by TheIncredibleMulk** [comment]
Tried two sources, home office is a MosaicTPC and sACN view running on other machines, yesterday I had an Elation Onyx NX2 (old version of the hardware) with the same issue.  
See two attached wireshark captures, 
- Onyx capture didn't have a filter just a raw capture, and it was on the Ethernet interface. My laptop was directly connected to the console, trying to eliminate devices that might have been causing problems.
- MTPC capture has the settings set that you requested, I did have sACNview listening in the background to make IGMP send me packets. WiFi and Ethernet share the same network so probably receiving on two interfaces. But I can turn WiFi off and still get the same error.

[sACNview-pcap.tar.gz](https://github.com/docsteer/sacnview/files/6246153/sACNview-pcap.tar.gz)

**Comment by marcusbirkin** [comment]
Thanks for these, if we look at the MTPC capture (with the 'any' interface filter) we do see that packets arrive twice.
For a demonstration of this select the first packet in the list with the filter "acn.dmx.seq_number == 140"
We see that both times sequence 140 comes around it's received twice, thus triggering the SeqErr.
![image](https://user-images.githubusercontent.com/5006518/113406745-ecfeb580-93a3-11eb-8a65-eece567cf1c3.png)

Now unfortunately what the 'any' interface capture doesn't show is the originating interface!
