### ISSUE TITLE
MSVCP140.dll missing, on PC.  MacApple says needs update

### ISSUE THREAD

**Issue by cfailor** [docsteer/sacnview#239]
I am on a PC, when I download, install and and launch I get message

 "the code execution cannot proceed because MSVCP140.dll was not found.  Reinstalling the program may fix this problem."

I tried reinstalling and restarting, but no luck.  any help would be appreciated

On my apple mac it will not open, because apple cannot check for malicious software.  says software needs to be updated.

any help would be appreciated

**Comment by marcusbirkin** [comment]
On the PC Install v2.1.1 and then upgrade

On the Mac, please read https://support.apple.com/en-gb/guide/mac-help/mchleab3a043/mac and follow the linked support article.
