### ISSUE TITLE
Big Display RGB not reliably updating when two or more are open

### ISSUE THREAD

**Issue by matt-pumplin** [docsteer/sacnview#241]
v2.1.2.  With two or more Big Displays, the one of them will sometimes "hang" on the values of its middle address ("Colour Address 2").  I haven't found a completely bulletproof reproducer but I was doing something like:

1. At a lighting console, patch some contiguous LED RGBW 8b fixtures.  
2. Fade all channels' colors the same way (I used an effect that applies to their "virtual" intensity; the lighting console then applies changes to color parameters to apparently change the overall intensity of the light))
3. Open two Big Displays
4. Notice that in one of the Big Displays, the middle digit "hangs" and the color of the digits matches this value, rather than what's shown in the Universe View.

I inspected a wireshark trace, which matches the values displayed in Universe View.  Please see attached .gif showing the result of this apparent bug.
![Big Display color issue](https://user-images.githubusercontent.com/32332797/120508117-12507580-c38d-11eb-992d-4f1ccd3af2b5.gif)

**Comment by marcusbirkin** [comment]
Thanks, the gif helped!
