### ISSUE TITLE
Feature Request - Universe View - Online/Offline column status

### ISSUE THREAD

**Issue by EVeik** [docsteer/sacnview#242]
Was using this to mock-up multiple sACN sources coming and going on a network and found myself squinting a lot at the Online column in Universe View.  Online and Offline text look very similar with 3 or more sources.

Was thinking it may be a good idea to add color to the font so at a glance, we can see online sources in Green text (just the Online column text) and offline sources in Red text.

Was wondering when a source has gone offline and comes back online, is it possible to have the text reflect that, such as "Online-Restored" or just restored or some such verbage that reflects that the source has gone and comeback
![2021-06-22 13_50_04-Window](https://user-images.githubusercontent.com/30304657/122982694-c9bf2300-d360-11eb-8ce8-58639c6733f9.png)
  

I realize Flicker Finder is good for that as well but when all levels return to the same level, I am more interested in whether the source actually left.  In this use-case, trying to troubleshoot IGMP Querier timing.

**Comment by marcusbirkin** [comment]
Are you aware of the logging window?
There is an option avaliable to show "Level Changes" and/or "Source Changes".
Perhaps setting this to simply log Source Changes is what you want?

**Comment by marcusbirkin** [comment]
0c56412d65eeab7d5cd4f1d0d55cc979becce3ce adds an additional colour and status of Yellow/Online (unstable) to a change already made in v2.2 (0c56412d65eeab7d5cd4f1d0d55cc979becce3ce) which moves online status to a more useful location and highlights with Green or Red
![image](https://user-images.githubusercontent.com/5006518/146644764-57510857-49e8-4ab9-b959-f6d3c4e5dfd9.png)

**Comment by docsteer** [comment]
Feature added in v2.2.0-beta.1
