### ISSUE TITLE
A Big Display 8 Bit can fail to update values when more than two are open.

### ISSUE THREAD

**Issue by matt-pumplin** [docsteer/sacnview#245]
Similar to Issue #241 but this time I'm just using 8 Bit Big Displays.
I have three DMX addresses that are bouncing between two incoming values.  Address 2's display seems to hang and not give all updates:
![Big Display 8 Bit hanging](https://user-images.githubusercontent.com/32332797/138507236-3d7831b0-0667-4aec-80cc-27e6ef1f08b8.gif)
When I change it to 16-bit, it does update properly).
At the start of the .gif, it's already at the wrong value - should be showing 179.

**Comment by matt-pumplin** [comment]
I'm seeing an issue using two 16-bit windows as well.  Looking forward to the fix when it comes available.

**Comment by docsteer** [comment]
v2.1.3 beta 1 is now released and on the website, and includes this fix.
