### ISSUE TITLE
Multiple sources in Universe View can make it look like a per-address source is active, when it is not

### ISSUE THREAD

**Issue by hinrichsenhans** [docsteer/sacnview#248]
Setup:

- Open two transmit tabs and a single Universe View in sACN 2.1.2
- Transmit tab 1: Universe 1, Per-Address Priority, press "..." and set all addresses to priority 0. Set Address 1 alone to 100.
- Transmit tab 2: Universe 1, Per-Address Priority, no changes to priority map (all at 100)
- Start transmitting in tab 1, bring the address 1 slider up slightly
- Universe View (U1): Note that only a single cell is active. Address 1 says it has a winning value from tab 1 at priority 100.
- Look at Address 2 - it has no sources
- Start transmitting in tab 2
- Universe View (U1) now shows for address 2 that there are two active sources. The winning source (from tab 2) at priority 100, and tab 1 at priority 0

![image](https://user-images.githubusercontent.com/10644584/146609657-ba6b6446-66e7-4120-8965-8d6ac82213a1.png)

Internally, I know per-address priority is setting the value to 0, so this is accurate. However, this makes it appear as if we do have that address patched. (It is an implementation detail that a value of 0 is the "not patched" value). Ideally we should show the single source, or show the inactive addresses consistently.

**Comment by RichardTea** [comment]
Do you actually mean Per-Address mode throughout?

Priority Mode "Per-Source" (default) is "per-universe", so there are no per-address priority values. The [...] button is disabled and _all_ addresses are 'patched' with the same priority.
In that situation, Per-Source priority 0 is an active value (least important).

**Comment by hinrichsenhans** [comment]
Whoops! Yes I do, I'll see if I can edit the original.

**Comment by docsteer** [comment]
Resolved in v2.2.0-beta.1
