### ISSUE TITLE
sACN sent to the incorrect multicast address will still be recognized

### ISSUE THREAD

**Issue by docsteer** [docsteer/sacnview#252]
If sACN is sent to the wrong multicast group (e.g. multicast data for universe 2 is sent to 239.255.0.1) the application will still recognize it as valid sACN.

We should either fail reception entirely in this case, or, show an error for the universe

**Comment by marcusbirkin** [comment]
This was, sort of, by design. It was a artifact of the unicast support.
Should we have a tickbox (enabled by default?) in preferences to allow reception on invalid multicast?

**Comment by docsteer** [comment]
I would vote for rejection by default - if I recall this caused confusion where someone was testing a device that didn't use multicast addresses correctly, sACNView showed it just fine but gateways wouldn't receive it. We don't want to encourage people to put hundreds of universes on one multicast address :-)

**Comment by marcusbirkin** [comment]
I'll skip the preferences option, it's getting full.... maybe later we have options to allow/disallow Broadcast/Multicast/Unicast/Wrong mutlicast/et cetera.
For now I'll just fix the bug!

**Comment by docsteer** [comment]
Resolved in v2.2.0-beta.1
