### ISSUE TITLE
Feature Request - Snapshot ~~All Discovered~~ large range of Universes

### ISSUE THREAD

**Issue by abbytutorow** [docsteer/sacnview#256]
Apologies if this has been asked before. I'd like to request a feature add - the ability to collect all discovered universes. I'd love to have this ability in both the Snapshot widget and the Multi-Universe Transmitter widget. Thanks for considering!

**Comment by marcusbirkin** [comment]
Discovered universes as in the extension to sACN that allows each source to publish a universe list (as implemented in the discovered universes tab) or scanning the network for all universes.

The latter is a bit of an issue, there are (over) 65k possible sACN universes, the act of scanning this range is very, very time consuming. It would need to join the multicast address, wait some time for a source, then move on to the next. In realistic terms maybe about 10 seconds per universe.
This can be sped up my parallel scanning, i.e. several universes at once. But there is a practical limit to the number of multicast addresses that can be joined at once - OS dependent, but maybe around the 30-40 region.

So yes it would be a really nice thing, and I've certainly looked into similar.....but it would be limited to the sACN extension option which has limited support from devices.

**Comment by marcusbirkin** [comment]
Topic updated after discussion with OP about use case.
A large number of universes need to be snapshotted, the range will be typed input.
Example of input format: 1,2,3,4,5-10

**Comment by docsteer** [comment]
Feature added in v2.2.0-beta.1
