### ISSUE TITLE
Missing hardware [physical] port

### ISSUE THREAD

**Issue by prwatGH** [docsteer/sacnview#257]
sACN view 2.1.2
Cannot see the actual physical LAN port on my laptop.
It is currently set to 10.101.49.1

**Comment by marcusbirkin** [comment]
sACNView runs a few checks to ensure suitablity of an interface for use, it hides unsuitable interfaces.
These tests are:
- Running 
  - The network interface is operational: configured "up" and (typically) physically connected to a network
- Up 
  - The network interface is "up" - enabled by administrative action 
    - A redundant check on _most_ plaforms due to also checking 'Running"
- Able to multicast 
  - The network interface supports multicasting) 
    - Check omited for loopback adapters
- Valid IPv4 address

Which platform are you operating on? There are different operations that can be performed on each plaform to determine interface suitability

**Comment by prwatGH** [comment]
Running a Sony Vaio laptop and Windows 7.

The port is visible and operational when I use DMXWorkshop.

Peter

**Comment by prwatGH** [comment]
OK, so now I have connected to my AL node, I can see the NIC interface.

To me, this is not intuitive - I should be able to see the interface 
even if there are no nodes attached.

DMX workshop offers me the NIC before I actually connect a device.

Another, possibly related issue is that the application is taking a long 
(10-20seconds) to start when I have the AL node connected to the NIC.

Peter

**Comment by prwatGH** [comment]
I have a single node connected to laptop. 
Via poe power injector. Trying to use sACNview to test node before shipping to site. 
Do not understand why you hide NIC
Peter

**Comment by marcusbirkin** [comment]
The interface must be up and running before starting sACNView.
