### ISSUE TITLE
Windows 10 Installer doesn't run vc_redist.x86 meaning that MSVC runtime components aren't installed for launch.

### ISSUE THREAD

**Issue by SamuelLouisCampbell** [docsteer/sacnview#259]
Pretty much as in the heading: 
Windows 10 Installer doesn't run vc_redist.x86 meaning that MSVC runtime components aren't installed for launch.

After running the installer the software exited complaining that MSVC140_1.dll or similar (Sorry I didn't make note) was missing. I looked in the files and saw that you have included the Microsoft installer. But I note that while it was noted in the install log, I never saw it being run. I ran it myself and hooray it's working. But other potential users may have less resilience.

**Comment by marcusbirkin** [comment]
Which version of sACNView was this with, I believe this was resolved in v2.1.3-beta.1

**Comment by marcusbirkin** [comment]
Likely duplicate of #235

**Comment by SamuelLouisCampbell** [comment]
Doh! Yes resolved in v2.1.3-beta.1, apologies for the duplicate and great work on the very useful tool!
