### ISSUE TITLE
Crash on sending 40 universes simultaneously (on Mac OS)

### ISSUE THREAD

**Issue by Bartel-C8** [docsteer/sacnview#261]
I am using version 2.1.2 on MacOS.

I get this crash (after a few seconds) after adding 40 universes at a time, using the multiple send window.
With the settings below:

![Screenshot 2022-05-18 at 10 12 20](https://user-images.githubusercontent.com/76486925/168990993-316e6335-64b9-4ec7-9511-f637ec7dff0f.png)

See crash dump.

[crashdumpSacn.txt](https://github.com/docsteer/sacnview/files/8714434/crashdumpSacn.txt)

What i noticed that for:
Effect Engine Universe 20
Effect Engine Universe 21
Effect Engine Universe 22

There are 2 threads created?

And for Universe 40, there is no thread created (yet)?

**Comment by marcusbirkin** [comment]
Could you try in v2.1.3-beta.1 ?

**Comment by Bartel-C8** [comment]
Works there! Thanks.

Did not see https://github.com/docsteer/sacnview/issues/246 ! Thanks!
