### ISSUE TITLE
sACNView for iOS?

### ISSUE THREAD

**Issue by idm** [docsteer/sacnview#262]
Is sACNView for iOS still available? I followed the [link](https://itunes.apple.com/us/app/sacnview/id1109906452) from [tomsteer.net](http://tomsteer.net) but got a message that the app is not available in my country or region (AU)

[https://itunes.apple.com/us/app/sacnview/id1109906452](https://itunes.apple.com/us/app/sacnview/id1109906452)

**Comment by docsteer** [comment]
Yes, unfortunately Apple changed a lot of things - direct usage of multicast is now increasingly difficult, and the income from the iOS app wasn't enough to cover my annual developer fees :-( I might revive it sometime in the future, but it's unrelated to the desktop version really, so closing this bug
