### ISSUE TITLE
fps counter issue

### ISSUE THREAD

**Issue by sstaub** [docsteer/sacnview#264]
It seems the fps counter count also DD startcode packages. The fps counter should work only for DMX values
not for priority per channel.
Maybe there should an extra fps field for DD packets.

**Comment by marcusbirkin** [comment]
How about the main FPS counter shows SC 0x00 (DMX), with a hover over tooltip showing other SC, and a combined total?
So as not to have too many specialist extra fields.

**Comment by sstaub** [comment]
That would nice if possible. In the moment I write a small Arduino library for sACN which also handles DD start code, that's the reason I realized this issue.

**Comment by marcusbirkin** [comment]
v2.1.2 already only counts DMX Dimmer data (SC 0x00) toward FPS counter.
https://github.com/docsteer/sacnview/blob/1d80f5bb2ef8bb40186ce117cc013f95f7e35e7c/src/sacn/sacnlistener.cpp#L537 is protected by https://github.com/docsteer/sacnview/blob/1d80f5bb2ef8bb40186ce117cc013f95f7e35e7c/src/sacn/sacnlistener.cpp#L487
