### ISSUE TITLE
Support Pathway Connectivity "Secure DMX Protocol" extension

### ISSUE THREAD

**Issue by marcusbirkin** [docsteer/sacnview#267]
There is an out of date [fork ](https://github.com/Pathway-Connectivity/secure-sacnview) only supporting the [Pathway Connectivity "Secure DMX Protocol"](https://pathway.acuitybrands.com/resources/network-security), full support should be added as a feature

**Comment by docsteer** [comment]
Resolved in v2.2.0-beta.1
