### ISSUE TITLE
Noob help, adapter support?

### ISSUE THREAD

**Issue by jlg89** [docsteer/sacnview#270]
I'm new to DMX, and trying to figure out if sACNView can help me do what I need to do.

The basic situation is that I'm replacing a Chauvet Stage Designer 50 DMX board with a Chauvet DMX-AN 2 Art-Net/sACN Node, controlled with Photon 2 on an iPad. Single universe, only a dozen or so devices, faders only, no colors etc. and all a 3-wire DMX bus. I'd like to be able to read the DMX data being sent on the DMX bus for the existing presets, so I can match those exactly in the Photon 2 config.

I have the DMX-AN configured to use sACN rather than Art-Net, and I can set it as an input or an output node. If I set it as an input, can I connect to it over the LAN with sACNView and read the values off of the bus?

**Comment by marcusbirkin** [comment]
Hi,

Yes when the DMX-AN is set to sACN mode, sACNView will interact with the DMX values.
When DMX-AN is configured to input, sACNView will show the incoming levels; and inversly when set to output, sACNView will control the outgoing DMX values.

FYI: There is also a tool, from the creators of Art-Net, that will allow you to perform the same but using Art-Net: https://artisticlicence.com/product/dmx-workshop/
