### ISSUE TITLE
Minor bug - typo in preferences restart dialog.

### ISSUE THREAD

**Issue by danielskeenan** [docsteer/sacnview#287]
In branch 2.2-dev (as of d2c092e), there is a typo in the dialog opened after changing a preference that requires restart:

![Restart requied](https://user-images.githubusercontent.com/4589231/218264003-29872492-c91b-412b-bb3e-0aafcf19f10b.png)

**Comment by docsteer** [comment]
Resolved in v2.2.0-beta.1
