### ISSUE TITLE
beta 2.2.0.1 - Window can get stuck off-screen

### ISSUE THREAD

**Issue by EVeik** [docsteer/sacnview#294]
Opening a window and accidentially dragging it "off-screen" can make it be inaccessible.  In this scenario there is no means to grab the window header to move it around.  There is also no means (that I am aware of) to close the window other than re-starting the program.

![image](https://user-images.githubusercontent.com/30304657/224148564-a171289d-53b3-48f9-8e24-c8ca563e4dbc.png)

**Comment by marcusbirkin** [comment]
Do you not get a scroll bar appear on the edge of the MDI area when this happens?

**Comment by EVeik** [comment]
I never knew that existed!  Yes the scroll bar is there.  Cancel this bug :)
