### ISSUE TITLE
Program Can Only Run on AMD64 Architecture

### ISSUE THREAD

**Issue by LSkulley** [docsteer/sacnview#310]
As the title says.

I am currently trying to create a DMX/Network monitor out of a Raspberry Pi to take with me on job sites, and have found this to be my primary stumbling block. Any support for ARM64 architecture has eluded me.

**Comment by marcusbirkin** [comment]
What steps have you taken to compile it, where does it fail?
Are you using pre-built Qt compiling from scratch?

sACNView is very much not limited to AMD64 architecture, it should compile with only modist tweaks on most platforms where Qt is supported.

**Comment by marcusbirkin** [comment]
Have a look at https://doc.qt.io/qtcreator/creator-targets.html
Kits are a collection of compilers, headers, et cetera; for your target platform. You will need to either download a kit or create a kit for your target platform.

As this is a Qt Creator usage issue, and not an sACNView issue, I'm going to close the issue. For further support I would recommend to post to a Qt and/or RPi specific forum.

**Comment by marcusbirkin** [comment]
Boot2qt is a full Linux embedded image, I doubt it has the required 3rd party libraries included by default.
You will need to add these to your image.
As to how this is done, that's beyond the scope of what we can help with.
