### ISSUE TITLE
Cannot see my GIO till I transmit

### ISSUE THREAD

**Issue by johnhart96** [docsteer/sacnview#61]
I have a GIO on my network that is transmitting sACN. I cant see this in sACNView till I transmit sACN direct from sACNView. View here: https://www.screencast.com/t/7cCDQtgY9

**Comment by johnhart96** [comment]
This turned out that it was firewall issue. It would be nice to see a warning that this has been previously blocked in windows firewall.

**Comment by docsteer** [comment]
RC3 adds a warning if the firewall is blocking the app, and the addition of a firewall exception by the installer (for Windows only at the moment)
