### ISSUE TITLE
Crash on accessing source during removal from universe list. Was: Crashes when non-continuous frames are sent

### ISSUE THREAD

**Issue by davek99** [docsteer/sacnview#68]
I am using the most recent build from your website (I did not build from git).  V2.0.0-RC2 (June 11th, 0217).  Running on Windows 7.  Using a Raspberry Pi running https://www.openlighting.org/ola/ to send sACN via their Python API.

For me, sACNView periodically crashes when the sACN source sends only a frame or two of sACN.  Seems to be just fine if sending continuous frames of sACN (about 100ms apart), but once that stops and goes back to only one (or periodic) frames the program crashes.

**Comment by marcusbirkin** [comment]
Hi,

Are you able to create a wireshark (https://www.wireshark.org/) log of the packets that can cause this issue?

Thanks,

Marcus

**Comment by marcusbirkin** [comment]
Not entirely resolved with #69

**Comment by davek99** [comment]
Here is a wireshark file of what was happening when it crashes.  Wireshark was started after my controller began sending sACN.  When the controller stops, sACN View crashes.
[OLA Crashes sACN View txt.txt](https://github.com/docsteer/sacnview/files/1168555/OLA.Crashes.sACN.View.txt.txt)

**Comment by marcusbirkin** [comment]
Please see if this is resolved within RC3

**Comment by marcusbirkin** [comment]
Closing issue as no further reports of issues and I can no longer reproduce in recent builds

**Comment by marcusbirkin** [comment]
Same base issue still present in 2.0.1 RC2
Reproducer:
() Start a source
() Wait for the source to appear in universe list
() Stop source
() Repeatedly click on source in universe list
() Crash as the source is removed

**Comment by docsteer** [comment]
Fix integrated in build 2.0.1 RC3
