### ISSUE TITLE
Dark Mode!

### ISSUE THREAD

**Issue by Lozzy0603** [docsteer/sacnview#91]
Beautiful updates to sACN viewer but needs a "dark mode", black backgrounds and white text to look real nice.
Thanks!

**Comment by docsteer** [comment]
Good idea for dark theatres - thanks! We will look at this for the 2.1 version.

**Comment by docsteer** [comment]
Implemented in 2.1 beta 1 - now available for download!

**Comment by Lozzy0603** [comment]
Epic! Thank you. Looks awesome!
