### ISSUE TITLE
sacnView does not start on my MacOS 10.9.5

### ISSUE THREAD

**Issue by sl1200mk2** [docsteer/sacnview#93]
Hi,
first, thank you for your terrific program :)

I can run it on windows, but on the mac, it doesn't even start (using the latest V2-RC4 available)...
here's the crash log:
https://pastebin.com/qF5txu58

best regards,
Nicolas

**Comment by marcusbirkin** [comment]
Hi Nicolas,

Unfortunately the SDK used (QT 5.9) doesn't support MacOS older than 10.10 Yosemite (https://doc.qt.io/qt-5/supported-platforms.html).
There is a bug in older versions of QT that prevent the uses of older QT versions.

Marcus

**Comment by sl1200mk2** [comment]
ah ok...
sorry for the noise and thank you for your answer.

++

**Comment by marcusbirkin** [comment]
You could compile from source with QT5.8, I think the bug may only affect Windows machine and machines utilising IPv6.

**Comment by sl1200mk2** [comment]
Hi Marcus,
I won't compile it as I do not specifically need it...
that said, here's my goal:
sacnView seems to be a great tool to monitor/generate E131. I'm planning training course about a software I've made and at early stage of the training course I'll present sacnView (with macOS 10.10 limits).

best regards,
nicolas
