### ISSUE TITLE
No unatteneded install

### ISSUE THREAD

**Issue by earlmaier** [docsteer/sacnview#95]
There are no command line switches for slient installs, which is useful for corporate deployment.  Also, for additional convenience add a /? or /help switch to the installer.

**Comment by marcusbirkin** [comment]
Hi,

Your in luck, the installer does contain a silent install option (but not documented.)

/S - Silent installation
/D={install path} - Set installation folder (Must be the last parameter on the command line and must not contain quotes even if the path contains blank spaces.)

**Comment by earlmaier** [comment]
Great! Thanks

**Comment by marcusbirkin** [comment]
Resolved in v2.0.0
