### ISSUE TITLE
Plus and minus keys on universe selection seem reversed

### ISSUE THREAD

**Issue by dmeltzer** [docsteer/sacnview#98]
Normally I'd expect the "plus" on the right and "minus" on the left.  Appears like thats the opposite, currently.  

![image](https://user-images.githubusercontent.com/3803132/33457250-e92c20d4-d5ef-11e7-9b78-0a8999df8550.png)

Is this intentional? If not I'll be happy to look at making a patch if it's easiest.

Thanks

**Comment by marcusbirkin** [comment]
Resolved in v2.0.0
